### ISSUE TITLE
Island border issue

### ISSUE THREAD

**Issue by ItzFel** [dim-pm-plugins/xSkyBlock#2]
![Screenshot_2020-11-03-10-42-08-024_com mojang minecraftpe](https://user-images.githubusercontent.com/62336632/97945239-dd158200-1dc1-11eb-936e-e304735ff16e.png)

**Comment by DimBis** [comment]
It's not an error it's a builtin features for limiting the size of the islands. You have to change the default world name to Hub to fix that issue

**Comment by DimBis** [comment]
I might make a configuration for that in the next update so I'll leave the enchantment label.

**Comment by plun1331** [comment]
@DimBis I think what he means is it sends the message 500 times

**Comment by DimBis** [comment]
Oh that's an easy fix
