### ISSUE TITLE
uh config??

### ISSUE THREAD

**Issue by BLAST1718** [dim-pm-plugins/xSkyBlock#5]

**Comment by plun1331** [comment]
Could you be more specific?

**Comment by DimBis** [comment]
I'm not thinking of maintaining this plugin as it's not getting any support, I'd accept pull requests for sure as long as they match up with the current code style.

**Comment by BLAST1718** [comment]
i mean add config and what do pull request do?

**Comment by plun1331** [comment]
> i mean add config and what do pull request do?

At this point you're basically asking how to use Github. Google it.

**Comment by BLAST1718** [comment]
bruh
